from typing import Protocol
from app.domain.models import Measurement, Event, Alert

class Repository(Protocol):
    def add_measurement(self, m: Measurement) -> None: ...
    def list_measurements(self, type: str | None, limit: int) -> list[Measurement]: ...
    def add_event(self, e: Event) -> None: ...
    def list_events(self, limit: int) -> list[Event]: ...
    def save_alert(self, a: Alert) -> None: ...
    def list_alerts(self, active_only: bool) -> list[Alert]: ...
    def reset(self) -> None: ...