"""initial_schema

Revision ID: db5b9f13b577
Revises: 
Create Date: 2026-09-24 11:15:54.973787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5b9f13b577'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Type',
    sa.Column('Id_Type', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('variete', sa.String(length=100), nullable=True),
    sa.Column('famille', sa.String(length=100), nullable=False),
    sa.Column('systeme_culture', sa.String(length=30), nullable=False),
    sa.Column('ph_min', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('ph_max', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('ec_min', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ec_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('temp_eau_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_eau_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_air_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_air_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidite_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidite_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('co2_min', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('co2_max', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('ppfd_min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ppfd_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('photoperiode_heures', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('cycle_culture_jours', sa.Integer(), nullable=True),
    sa.Column('rendement_min_kg_m2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('rendement_max_kg_m2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('besoin_eau_l_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('Id_Type')
    )
    op.create_table('Plant',
    sa.Column('Id_Plant', sa.Integer(), nullable=False),
    sa.Column('date_semis', sa.Date(), nullable=True),
    sa.Column('date_plantation', sa.Date(), nullable=True),
    sa.Column('date_recolte_prevue', sa.Date(), nullable=True),
    sa.Column('quantite', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unite_quantite', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('Id_Type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_Type'], ['Type.Id_Type'], ),
    sa.PrimaryKeyConstraint('Id_Plant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Plant')
    op.drop_table('Type')
    # ### end Alembic commands ###
